### ISSUE TITLE
ERROR: sorry, it was not possible to establish a connection to the server.

### ISSUE THREAD

**Issue by Yuribenjamin** [gouv3a/nipe#47]
I got this error when i started the service using command `perl nipe.pl start` && `sudo perl nipe.pl start`
os : Ubuntu 18.04.1 LTS
perl -v : v5.26.1
iptables: v1.6.1
thanks for advance

**Comment by APoniatowski** [comment]
same issue here. same specs as above

**Comment by GouveaHeitor** [comment]
Hi @Yuribenjamin and @APoniatowski,

I've made some changes to the Nipe code recently, can you see if this error has been fixed?

Thx

**Comment by azizaashiq** [comment]
Same issue on Termux
![Screenshot_2019-05-19-10-02-52-929_com termux](https://user-images.githubusercontent.com/35604655/57977785-59c16e80-7a1d-11e9-86ea-85fa03e29006.png)

**Comment by Yuribenjamin** [comment]
the same error occurred.
specs update
os : Ubuntu 19.04 (Disco Dingo)
perl -v : v5.28.1
iptables: v1.6.1

**Comment by GouveaHeitor** [comment]
Hi Guys,

I think I got this error fixed, can someone please confirm it?

Thx.

**Comment by Yuribenjamin** [comment]
`yuri@Ibrahim:~/projects/nipe$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
yuri@Ibrahim:~/projects/nipe$ perl -v

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi
(with 67 registered patches, see perl -V for more detail)

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

yuri@Ibrahim:~/projects/nipe$ iptables --version
iptables v1.6.1
yuri@Ibrahim:~/projects/nipe$ perl nipe.pl start
yuri@Ibrahim:~/projects/nipe$ perl nipe.pl status

[!] ERROR: sorry, it was not possible to establish a connection to the server.

yuri@Ibrahim:~/projects/nipe$ perl nipe.pl stop
yuri@Ibrahim:~/projects/nipe$ sudo perl nipe.pl start
yuri@Ibrahim:~/projects/nipe$ sudo perl nipe.pl status

[!] ERROR: sorry, it was not possible to establish a connection to the server.
`

**Comment by Yuribenjamin** [comment]
![Screenshot from 2019-07-27 13-36-16](https://user-images.githubusercontent.com/25421760/61993948-1b2ade80-b074-11e9-8d1f-6b52574d6262.png)

**Comment by Yuribenjamin** [comment]
it working now!
in nipe/lib/Nipe/Functions.pm line 22 the install fn cannot be detecting the operating system so I did it manually then I started the service and it works!
page 2/2
![Screenshot from 2019-07-27 14-25-35](https://user-images.githubusercontent.com/25421760/61994536-d4d97d80-b07b-11e9-91da-476a1a489376.png)

**Comment by cheyennespirit** [comment]
The same error on Manjaro.
